// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//TRY TO GENERATE YOUR OWN FIREBASE OPTIONS FILE

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'VOTRE CLE API',
    appId: 'ID DU SYSTEME',
    messagingSenderId: '990471821524',
    projectId: 'samutaxi-68b0e',
    authDomain: 'samutaxi-68b0e.firebaseapp.com',
    storageBucket: 'samutaxi-68b0e.firebasestorage.app',
    measurementId: 'G-LEJPLVDX7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'VOTRE CLE API',
    appId: 'ID DU SYSTEME',
    messagingSenderId: '990471821524',
    projectId: 'samutaxi-68b0e',
    storageBucket: 'samutaxi-68b0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'VOTRE CLE API',
    appId: 'ID DU SYSTEME',
    messagingSenderId: '990471821524',
    projectId: 'samutaxi-68b0e',
    storageBucket: 'samutaxi-68b0e.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'VOTRE CLE API',
    appId: 'ID DU SYSTEME',
    messagingSenderId: '990471821524',
    projectId: 'samutaxi-68b0e',
    storageBucket: 'samutaxi-68b0e.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'VOTRE CLE API',
    appId: 'ID DU SYSTEME',
    messagingSenderId: '990471821524',
    projectId: 'samutaxi-68b0e',
    authDomain: 'samutaxi-68b0e.firebaseapp.com',
    storageBucket: 'samutaxi-68b0e.firebasestorage.app',
    measurementId: 'G-9147KPVX9D',
  );
}
